### ISSUE TITLE
Trait bound `BigDecimal: From<(BigInt, i64)>` is no longer satisfied after update from `0.2.0` to `0.2.1`

### ISSUE THREAD

**Issue by piodul** [akubera/bigdecimal-rs#83]
This code used to compile with version `0.2.0`:

```rust
use bigdecimal::BigDecimal;
use num_bigint::{BigInt, Sign}; // num-bigint = "0.3"

fn main() {
    let scale = 5i64;
    let int_value = BigInt::new(Sign::Plus, vec![1]);
    let big_decimal = BigDecimal::from((int_value, scale));
    println!("{:?}", big_decimal);
}
```

...but no longer does after update to `0.2.1` and fails with the following error:

```
error[E0277]: the trait bound `BigDecimal: From<(BigInt, i64)>` is not satisfied
 --> src/main.rs:7:23
  |
7 |     let big_decimal = BigDecimal::from((int_value, scale));
  |                       ^^^^^^^^^^^^^^^^ the trait `From<(BigInt, i64)>` is not implemented for `BigDecimal`
  |
  = help: the following implementations were found:
            <BigDecimal as From<(num_bigint::bigint::BigInt, i64)>>
            <BigDecimal as From<i16>>
            <BigDecimal as From<i32>>
            <BigDecimal as From<i64>>
          and 6 others
  = note: required by `from`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

This broke the build of the `scylla` crate: https://github.com/scylladb/scylla-rust-driver/issues/286
